### PR TITLE
Addon and updates

### PR DESCRIPTION
**Pull request by mikemartincode**
I made some changes that I needed for development.

If you see use in them you can merge the PR.

In specific I added addons and changed the create-stories script to include them.

The addons provide advanced functionality including having the example JSX inside storybook.

Also updated some dependencies.

### CODE REVIEW

**Comment by mikemartincode** [comment]
Awesome, I will also be keeping it relevant with the new Ant Design changes with theme variables.

 I will PR again when I finished it.

I generally use eslint if you want to include that as well.

**Comment by minheq** [comment]
oh yes! forgot about eslint, that would be great as well 👍 

Are you gonna continue from this PR? I am fine with that :)

**Comment by mikemartincode** [comment]
I may add more to it. I have an idea on how to write an actual theme generator after I am done this project I am currently on. If you want we can tackle that together.

**Comment by minheq** [comment]
@mikemartincode thanks a lot for ur contribution, this looks amazing :D I pushed few cosmetic changes to master

**Pull request merged**
